import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:path/path.dart' as p;

import '../db/database.dart';
import '../providers/entity_photos_provider.dart';
import '../providers/vault_provider.dart';
import 'thumbnail_image.dart';

/// Horizontal photo strip + "add" button for any entity (item, location,
/// recipe, task). Displays thumbnails generated by [ThumbnailService].
///
/// Usage:
/// ```dart
/// EntityPhotoSection(entityId: item.id, entityType: 'item')
/// ```
class EntityPhotoSection extends ConsumerWidget {
  final String entityId;
  final String entityType;

  const EntityPhotoSection({
    super.key,
    required this.entityId,
    required this.entityType,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final photosAsync = ref.watch(entityPhotosProvider(entityId));

    return photosAsync.when(
      loading: () => const SizedBox.shrink(),
      error: (e, st) => const SizedBox.shrink(),
      data: (photos) => _PhotoStrip(
        photos: photos,
        entityId: entityId,
        entityType: entityType,
      ),
    );
  }
}

class _PhotoStrip extends ConsumerWidget {
  final List<EntityPhoto> photos;
  final String entityId;
  final String entityType;

  const _PhotoStrip({
    required this.photos,
    required this.entityId,
    required this.entityType,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final cs = Theme.of(context).colorScheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Text('Fotos', style: Theme.of(context).textTheme.titleSmall),
            const Spacer(),
            TextButton.icon(
              onPressed: () => _addPhoto(context, ref),
              icon: const Icon(Icons.add_a_photo_outlined, size: 16),
              label: const Text('Hinzufügen'),
              style: TextButton.styleFrom(
                  visualDensity: VisualDensity.compact),
            ),
          ],
        ),
        if (photos.isEmpty)
          GestureDetector(
            onTap: () => _addPhoto(context, ref),
            child: Container(
              height: 80,
              decoration: BoxDecoration(
                color: cs.surfaceContainerHighest.withValues(alpha: 0.4),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(
                    color: cs.outlineVariant, style: BorderStyle.solid),
              ),
              child: Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(Icons.add_photo_alternate_outlined,
                        color: cs.onSurfaceVariant),
                    const SizedBox(height: 4),
                    Text('Fotos hinzufügen',
                        style: TextStyle(
                            fontSize: 12, color: cs.onSurfaceVariant)),
                  ],
                ),
              ),
            ),
          )
        else
          SizedBox(
            height: 100,
            child: ListView.separated(
              scrollDirection: Axis.horizontal,
              itemCount: photos.length + 1,
              separatorBuilder: (context, i) => const SizedBox(width: 6),
              itemBuilder: (context, i) {
                if (i == photos.length) {
                  return _AddTile(onTap: () => _addPhoto(context, ref));
                }
                return _PhotoTile(
                  photo: photos[i],
                  allPhotos: photos,
                  initialIndex: i,
                );
              },
            ),
          ),
      ],
    );
  }

  Future<void> _addPhoto(BuildContext context, WidgetRef ref) async {
    final source = await showModalBottomSheet<ImageSource>(
      context: context,
      builder: (ctx) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Icon(Icons.photo_camera_outlined),
              title: const Text('Kamera'),
              onTap: () => Navigator.of(ctx).pop(ImageSource.camera),
            ),
            ListTile(
              leading: const Icon(Icons.photo_library_outlined),
              title: const Text('Galerie'),
              onTap: () => Navigator.of(ctx).pop(ImageSource.gallery),
            ),
          ],
        ),
      ),
    );
    if (source == null || !context.mounted) return;
    await ref.read(entityPhotoOpsProvider.notifier).addPhoto(
          entityId: entityId,
          entityType: entityType,
          source: source,
        );
  }
}

// ── Add tile ──────────────────────────────────────────────────────────────────

class _AddTile extends StatelessWidget {
  final VoidCallback onTap;
  const _AddTile({required this.onTap});

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return GestureDetector(
      onTap: onTap,
      child: Container(
        width: 72,
        decoration: BoxDecoration(
          color: cs.surfaceContainerHighest.withValues(alpha: 0.5),
          borderRadius: BorderRadius.circular(8),
        ),
        child: Icon(Icons.add_a_photo_outlined,
            color: cs.onSurfaceVariant),
      ),
    );
  }
}

// ── Thumbnail tile ────────────────────────────────────────────────────────────

class _PhotoTile extends ConsumerWidget {
  final EntityPhoto photo;
  final List<EntityPhoto> allPhotos;
  final int initialIndex;

  const _PhotoTile({
    required this.photo,
    required this.allPhotos,
    required this.initialIndex,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final vaultPath = ref.watch(vaultPathProvider);

    return GestureDetector(
      onTap: () => _openViewer(context, ref),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(8),
        child: SizedBox(
          width: 100,
          height: 100,
          child: vaultPath != null
              ? ThumbnailImage(
                  sourcePath: p.join(vaultPath, photo.photoPath),
                  width: 100,
                  height: 100,
                  fit: BoxFit.cover,
                )
              : Container(color: Colors.black12),
        ),
      ),
    );
  }

  void _openViewer(BuildContext context, WidgetRef ref) {
    Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (_) => _PhotoViewerScreen(
          photos: allPhotos,
          initialIndex: initialIndex,
        ),
      ),
    );
  }
}

// ── Full-screen photo viewer ──────────────────────────────────────────────────

class _PhotoViewerScreen extends ConsumerStatefulWidget {
  final List<EntityPhoto> photos;
  final int initialIndex;

  const _PhotoViewerScreen({
    required this.photos,
    required this.initialIndex,
  });

  @override
  ConsumerState<_PhotoViewerScreen> createState() => _PhotoViewerScreenState();
}

class _PhotoViewerScreenState extends ConsumerState<_PhotoViewerScreen> {
  late int _current;
  late PageController _pageCtrl;

  @override
  void initState() {
    super.initState();
    _current = widget.initialIndex;
    _pageCtrl = PageController(initialPage: widget.initialIndex);
  }

  @override
  void dispose() {
    _pageCtrl.dispose();
    super.dispose();
  }

  EntityPhoto get _photo => widget.photos[_current];

  @override
  Widget build(BuildContext context) {
    final vaultPath = ref.watch(vaultPathProvider);
    final fmt = DateFormat.yMMMd('de_DE').add_Hm();

    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        title: Text(
          fmt.format(_photo.createdAt),
          style: const TextStyle(fontSize: 14),
        ),
        actions: [
          if (_photo.caption != null)
            IconButton(
              icon: const Icon(Icons.edit_outlined),
              tooltip: 'Beschriftung bearbeiten',
              onPressed: () => _editCaption(context),
            ),
          IconButton(
            icon: const Icon(Icons.add_comment_outlined),
            tooltip: 'Beschriftung',
            onPressed: () => _editCaption(context),
          ),
          IconButton(
            icon: const Icon(Icons.delete_outline),
            tooltip: 'Löschen',
            onPressed: () => _confirmDelete(context),
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: PageView.builder(
              controller: _pageCtrl,
              itemCount: widget.photos.length,
              onPageChanged: (i) => setState(() => _current = i),
              itemBuilder: (context, i) {
                final ph = widget.photos[i];
                final fullPath = vaultPath != null
                    ? p.join(vaultPath, ph.photoPath)
                    : null;
                return InteractiveViewer(
                  child: Center(
                    child: fullPath != null && File(fullPath).existsSync()
                        ? Image.file(File(fullPath))
                        : const Icon(Icons.broken_image_outlined,
                            color: Colors.white38, size: 64),
                  ),
                );
              },
            ),
          ),
          if (_photo.caption != null && _photo.caption!.isNotEmpty)
            Container(
              color: Colors.black87,
              width: double.infinity,
              padding:
                  const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
              child: Text(
                _photo.caption!,
                style: const TextStyle(color: Colors.white70),
              ),
            ),
          if (widget.photos.length > 1)
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 8),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: List.generate(
                  widget.photos.length,
                  (i) => Container(
                    margin: const EdgeInsets.symmetric(horizontal: 3),
                    width: i == _current ? 10 : 6,
                    height: 6,
                    decoration: BoxDecoration(
                      color: i == _current
                          ? Colors.white
                          : Colors.white38,
                      borderRadius: BorderRadius.circular(3),
                    ),
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }

  Future<void> _editCaption(BuildContext context) async {
    final ctrl = TextEditingController(text: _photo.caption ?? '');
    final result = await showDialog<String?>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Beschriftung'),
        content: TextField(
          controller: ctrl,
          autofocus: true,
          decoration:
              const InputDecoration(hintText: 'Beschriftung eingeben...'),
          maxLines: 3,
        ),
        actions: [
          TextButton(
              onPressed: () => Navigator.of(ctx).pop(null),
              child: const Text('Abbrechen')),
          TextButton(
              onPressed: () => Navigator.of(ctx).pop(''),
              child: const Text('Löschen')),
          FilledButton(
              onPressed: () => Navigator.of(ctx).pop(ctrl.text.trim()),
              child: const Text('Speichern')),
        ],
      ),
    );
    ctrl.dispose();
    if (result == null || !context.mounted) return;
    await ref.read(entityPhotoOpsProvider.notifier).updateCaption(
          _photo,
          result.isEmpty ? null : result,
        );
    if (context.mounted) setState(() {});
  }

  Future<void> _confirmDelete(BuildContext context) async {
    final ok = await showDialog<bool>(
          context: context,
          builder: (ctx) => AlertDialog(
            title: const Text('Foto löschen?'),
            content:
                const Text('Das Foto wird unwiderruflich gelöscht.'),
            actions: [
              TextButton(
                  onPressed: () => Navigator.of(ctx).pop(false),
                  child: const Text('Abbrechen')),
              FilledButton(
                  style: FilledButton.styleFrom(
                      backgroundColor:
                          Theme.of(ctx).colorScheme.error),
                  onPressed: () => Navigator.of(ctx).pop(true),
                  child: const Text('Löschen')),
            ],
          ),
        ) ??
        false;
    if (!ok || !context.mounted) return;
    await ref
        .read(entityPhotoOpsProvider.notifier)
        .deletePhoto(_photo);
    if (context.mounted) Navigator.of(context).pop();
  }
}
